import type { ModelPricing } from "./types.js";

/**
 * Fallback seed data for known Copilot SDK models.
 * Used when the GitHub API and docs page scraping both fail at startup.
 * Pricing data sourced from GitHub Copilot docs (June 2025).
 * Token multipliers: price_per_1M_tokens / 10
 */
export const SEED_MODELS: Omit<ModelPricing, "updatedAt">[] = [
	{
		id: "gpt-4o-mini",
		displayName: "OpenAI GPT-4o mini",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.015,
		tokenOutputMultiplier: 0.06,
		cachedInputMultiplier: 0.0075,
		tier: "trivial",
		available: true,
	},
	{
		id: "gpt-4o",
		displayName: "OpenAI GPT-4o",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.25,
		tokenOutputMultiplier: 1.0,
		cachedInputMultiplier: 0.125,
		tier: "trivial",
		available: true,
	},
	{
		id: "gpt-5-mini",
		displayName: "GPT-5 mini",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.025,
		tokenOutputMultiplier: 0.2,
		cachedInputMultiplier: 0.0025,
		tier: "trivial",
		available: true,
	},
	{
		id: "gpt-5.3-codex",
		displayName: "GPT-5.3-Codex",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.175,
		tokenOutputMultiplier: 1.4,
		cachedInputMultiplier: 0.0175,
		tier: "premium",
		available: true,
	},
	{
		id: "gpt-5.4",
		displayName: "GPT-5.4",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.25,
		tokenOutputMultiplier: 1.5,
		cachedInputMultiplier: 0.025,
		tier: "premium",
		available: true,
	},
	{
		id: "gpt-5.4-mini",
		displayName: "GPT-5.4 mini",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.075,
		tokenOutputMultiplier: 0.45,
		cachedInputMultiplier: 0.0075,
		tier: "premium",
		available: true,
	},
	{
		id: "gpt-5.5",
		displayName: "GPT-5.5",
		premiumMultiplier: 57.0,
		tokenInputMultiplier: 0.5,
		tokenOutputMultiplier: 3.0,
		cachedInputMultiplier: 0.05,
		tier: "ultra",
		available: true,
	},
	{
		id: "claude-sonnet-4",
		displayName: "Claude Sonnet 4",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.3,
		tokenOutputMultiplier: 1.5,
		cachedInputMultiplier: 0.03,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-sonnet-4.5",
		displayName: "Claude Sonnet 4.5",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.3,
		tokenOutputMultiplier: 1.5,
		cachedInputMultiplier: 0.03,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-sonnet-4.6",
		displayName: "Claude Sonnet 4.6",
		premiumMultiplier: 9.0,
		tokenInputMultiplier: 0.3,
		tokenOutputMultiplier: 1.5,
		cachedInputMultiplier: 0.03,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-haiku-4.5",
		displayName: "Claude Haiku 4.5",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.1,
		tokenOutputMultiplier: 0.5,
		cachedInputMultiplier: 0.01,
		tier: "trivial",
		available: true,
	},
	{
		id: "claude-opus-4.5",
		displayName: "Claude Opus 4.5",
		premiumMultiplier: 15.0,
		tokenInputMultiplier: 0.5,
		tokenOutputMultiplier: 2.5,
		cachedInputMultiplier: 0.05,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-opus-4.6",
		displayName: "Claude Opus 4.6",
		premiumMultiplier: 27.0,
		tokenInputMultiplier: 0.5,
		tokenOutputMultiplier: 2.5,
		cachedInputMultiplier: 0.05,
		tier: "ultra",
		available: true,
	},
	{
		id: "claude-opus-4.7",
		displayName: "Claude Opus 4.7",
		premiumMultiplier: 27.0,
		tokenInputMultiplier: 0.5,
		tokenOutputMultiplier: 2.5,
		cachedInputMultiplier: 0.05,
		tier: "ultra",
		available: true,
	},
	{
		id: "claude-opus-4.8",
		displayName: "Claude Opus 4.8",
		premiumMultiplier: 27.0,
		tokenInputMultiplier: 0.5,
		tokenOutputMultiplier: 2.5,
		cachedInputMultiplier: 0.05,
		tier: "ultra",
		available: true,
	},
	{
		id: "gemini-2.5-pro",
		displayName: "Gemini 2.5 Pro",
		premiumMultiplier: 1.0,
		tokenInputMultiplier: 0.125,
		tokenOutputMultiplier: 1.0,
		cachedInputMultiplier: 0.0125,
		tier: "fast",
		available: true,
	},
	{
		id: "gemini-3-flash",
		displayName: "Gemini 3 Flash",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.05,
		tokenOutputMultiplier: 0.3,
		cachedInputMultiplier: 0.005,
		tier: "trivial",
		available: true,
	},
	{
		id: "gemini-3.1-pro",
		displayName: "Gemini 3.1 Pro",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.2,
		tokenOutputMultiplier: 1.2,
		cachedInputMultiplier: 0.02,
		tier: "premium",
		available: true,
	},
	{
		id: "gemini-3.5-flash",
		displayName: "Gemini 3.5 Flash",
		premiumMultiplier: 14.0,
		tokenInputMultiplier: 0.15,
		tokenOutputMultiplier: 0.9,
		cachedInputMultiplier: 0.015,
		tier: "premium",
		available: true,
	},
	{
		id: "raptor-mini",
		displayName: "Raptor mini",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.025,
		tokenOutputMultiplier: 0.2,
		cachedInputMultiplier: 0.0025,
		tier: "trivial",
		available: true,
	},
	{
		id: "mai-code-1-flash",
		displayName: "MAI-Code-1-Flash",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.075,
		tokenOutputMultiplier: 0.45,
		cachedInputMultiplier: 0.0075,
		tier: "trivial",
		available: true,
	},
];
