import type { ModelPricing } from "./types.js";

/**
 * Fallback seed data for known Copilot SDK models.
 * Used when the GitHub API and docs page scraping both fail at startup.
 * Pricing data sourced from GitHub docs (June 2025).
 */
export const SEED_MODELS: Omit<ModelPricing, "updatedAt">[] = [
	{
		id: "gpt-4o-mini",
		displayName: "OpenAI GPT-4o mini",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.015,
		tokenOutputMultiplier: 0.06,
		cachedInputMultiplier: 0.0075,
		tier: "trivial",
		available: true,
	},
	{
		id: "gpt-4o",
		displayName: "OpenAI GPT-4o",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: 0.25,
		tokenOutputMultiplier: 1.0,
		cachedInputMultiplier: 0.125,
		tier: "trivial",
		available: true,
	},
	{
		id: "gpt-5-mini",
		displayName: "GPT-5 mini",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "trivial",
		available: true,
	},
	{
		id: "claude-sonnet-4",
		displayName: "Claude Sonnet 4",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: 0.6,
		tokenOutputMultiplier: 2.4,
		cachedInputMultiplier: null,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-haiku-4.5",
		displayName: "Claude Haiku 4.5",
		premiumMultiplier: 0.33,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "trivial",
		available: true,
	},
	{
		id: "gemini-2.5-pro",
		displayName: "Gemini 2.5 Pro",
		premiumMultiplier: 1.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "fast",
		available: true,
	},
	{
		id: "gpt-5.1",
		displayName: "GPT-5.1",
		premiumMultiplier: 3.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "standard",
		available: true,
	},
	{
		id: "gpt-5.2",
		displayName: "GPT-5.2",
		premiumMultiplier: 3.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "standard",
		available: true,
	},
	{
		id: "gpt-5.4",
		displayName: "GPT-5.4",
		premiumMultiplier: 6.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-opus-4.5",
		displayName: "Claude Opus 4.5",
		premiumMultiplier: 15.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "premium",
		available: true,
	},
	{
		id: "claude-opus-4.6",
		displayName: "Claude Opus 4.6",
		premiumMultiplier: 27.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "ultra",
		available: true,
	},
	{
		id: "claude-opus-4.7",
		displayName: "Claude Opus 4.7",
		premiumMultiplier: 27.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "ultra",
		available: true,
	},
	{
		id: "gpt-5.5",
		displayName: "GPT-5.5",
		premiumMultiplier: 57.0,
		tokenInputMultiplier: null,
		tokenOutputMultiplier: null,
		cachedInputMultiplier: null,
		tier: "ultra",
		available: true,
	},
];
